strings: array [0..11] of String = (
    'Rok 2419,'~,                                  // screen 1
    'Imperium Zjednoczonej Ziemi wciąż walczy'~,  // screen 2
    'Po ośmiu latach w armii nareszcie'~,         // screen 3
    'zakończyłeś swój kontrakt.'~,                // screen 3
    'Od dawna marzyłeś o własnym'~,               // screen 4
    'przedsięwzięciu i możliwości robienia'~,   // screen 4
    'co się chce.'~,                              // screen 4
    'Za otrzymany czek byłeś w stanie kupić'~,    // screen 5
    'najtańszy statek i jeszcze zostało Ci'~,       // screen 5
    'trochę gotówki.'~,                           // screen 5
    'Od Ciebie zależy, gdzie się teraz udasz.'~,  // screen 6
    ' Naciśnij spację, aby kontynuować '*~
);

  creditstxt: array [0..9] of String = (
    'Programowanie'~,
    'MADRAFi'~,
    ''~,
    'Grafika'~,
    'Broniu KAZ'~,
    'MADRAFi'~,
    ''~,
    'Muzyka'~,
    'Caruso'~,
    ''~
    
);