strings: array [0..11] of String = (
    'Rok 2419,'~,                                  // screen 1
    'Imperium Zjednoczonej Ziemi wci'#2''#26' walczy'~,  // screen 2
    'Po o'#9'miu latach w armii nareszcie'~,         // screen 3
    'zako'#14'czy'#12'e'#9' sw'#15'j kontrakt.'~,                // screen 3
    'Od dawna marzy'#12'e'#9' o w'#12'asnym'~,               // screen 4
    'przedsi'#5'wzi'#5'ciu i pe'#12'nej niezale'#26'no'#9'ci.'~,   // screen 4
    ''~,                                          // screen 4
    'Za otrzymany czek by'#12'e'#9' w stanie kupi'#3''~,    // screen 5
    'najta'#14'szy statek i jeszcze zosta'#12'o Ci'~,       // screen 5
    'troch'#5' got'#15'wki.'~,                           // screen 5
    'Od Ciebie zale'#26'y, gdzie si'#5' teraz udasz.'~,  // screen 6
    ' Naci'#9'nij spacj'#5', aby kontynuowa'#3' '*~
);

  creditstxt: array [0..8] of TString = (
    'Programowanie'~,
    'MADRAFi'~,
    ''~,
    'Grafika'~,
    'Broniu KAZ'~,
    'MADRAFi'~,
    ''~,
    'Muzyka'~,
    'Caruso'~
    
);
