
locations: array [0..NUMBEROFLOCATIONS-1] of TString = (
'Port Alistair'~,
'Glum Hex'~,
'Gas Mine 158'~,
'Ambiguous  Lab'~,
'Kudrow Ore'~,
'Mining Area 147'~,
'Hydro Harvest'~,
'Hikers Research'~,
'Oasis Depot'~,
'LKRM-Highdust'~,
'Yantar-4K2M'~,
'Tycho Station'~,
'Lourvil'~,
'LKRM-Westforge'~,
'LKRM-Sandy'~,
'Cloud City'~,
'Area 64'~,
'Cargo Depot'~,
'CyberTech'~,
'Fobos'~,
'Deep Space 41'~

);
