
ships: array [0..(NUMBEROFSHIPS * MAXSHIPPARAMETERS)-1] of TString = (
'SRV',0,10,200,28,231,
'Cutlass Black',1,46,220,29,226,
'Constellation',2,96,190,61,439,
'Freelancer Max',3,122,205,38,336,
'Reclaimer',4,180,80,155,9500,
'Hull B',3,384,60,49,387,
'Caterpillar',1,577,100,111,1608,
'C2 Hercules',5,624,135,94,1410,
'Idris-P',4,995,80,233,37310,
'Carrack',6,1000,120,123,4397,
'Merchantman',7,3584,90,160,9635,
'Hull C',3,4608,50,125,886
);

prodmatrix: array [0..7] of TString = (
  'Argo Astronautics',
  'Drake Interplanetary',
  'Roberts Space Industries',
  'Musashi Industrial',
  'Aegis Dynamics',
  'Crusader Industries',
  'Anvil Aerospace',
  'Banu'
);
