
ships: array [0..(NUMBEROFSHIPS * MAXSHIPPARAMETERS)-1] of TString = (
  'C-35 Osprey',0,10,200,28,231,
  'Raider',1,46,240,29,226,
  'Commando',2,96,180,61,439,
  'Antares Max',3,122,205,38,336,
  'Dreamlifter',4,180,80,155,9500,
  'Cargo Hull C1',3,384,60,49,387,
  'Griffin',1,577,100,111,1608,
  'Hercules',5,624,135,94,1410,
  'Starlifter',4,995,70,233,3731,
  'Spartan',6,1000,120,123,4397,
  'Merchant',7,3584,55,160,9635,
  'Cargo Hull C2',3,4608,45,125,886
);

prodmatrix: array [0..7] of TString = (
  'Ergon Astro',
  'Drago Interplanetary',
  'Real Space Industries',
  'Mitsui Industrial',
  'Aero Dynamics',
  'Aerospace Crusaders',
  'Anvil Industries',
  'Bantu'

);
