
ships: array [0..(NUMBEROFSHIPS * MAXSHIPPARAMETERS)-1] of TString = (
  'C-35 Osprey'~,'00','10','300','25','200','300','02',
  'Raider'~,'01','46','240','35','240','450','04',
  'Commando'~,'02','96','150','62','439','600','08',
  'Antares Max'~,'03','122','220','38','336','720','04',
  'Dreamlifter'~,'04','180','80','155','950','900','20',
  'Cargo Hull C1'~,'03','384','25','89','387','750','27',
  'Griffin'~,'01','577','100','111','1608','1000','14',
  'Hercules'~,'05','624','135','94','1410','950','11',
  'Starlifter'~,'04','970','70','233','3731','1200','28',
  'Spartan'~,'06','1000','120','123','4397','1600','14',
  'Merchant'~,'07','3584','55','160','9635','2500','23',
  'Cargo Hull C2'~,'03','4608','20','125','886','1000','36'

);

prodmatrix: array [0..7] of TString = (
  'Ergon Astro'~,
  'Drago Interplanetary'~,
  'Real Space Industries'~,
  'Mitsui Industrial'~,
  'Aero Dynamics'~,
  'Aerospace Crusaders'~,
  'Anvil Industries'~,
  'Bantu'~

);
