
ships: array [0..(NUMBEROFSHIPS * MAXSHIPPARAMETERS)-1] of TString = (

    'C-35 Osprey'~,'0','10','300','25','200','300','1',
    'Raider'~,'1','46','240','35','240','450','3',
    'Commando'~,'2','96','150','62','439','600','7',
    'Antares Max'~,'3','122','220','38','336','720','4',
    'Dreamlifter'~,'4','180','80','155','950','900','13',
    'Cargo Hull C1'~,'3','384','25','89','387','750','17',
    'Griffin'~,'1','577','100','111','1608','1000','12',
    'Hercules'~,'5','624','135','94','1410','950','10',
    'Starlifter'~,'4','970','70','233','3731','1200','25',
    'Spartan'~,'6','1000','120','123','4397','1600','13',
    'Merchant'~,'7','3584','140','260','6295','2500','18',
    'Cargo Hull C2'~,'3','4608','20','125','886','1000','29'

);

prodmatrix: array [0..7] of TString = (
  'Ergon Astro'~,
  'Drago Interplanetary'~,
  'Vostok Company'~,
  'Mitsui Industries'~,
  'Aero Dynamics'~,
  'Aerospace Crusaders'~,
  'Anvil Corporation'~,
  'Space Shipment'~

);
