strings: array [0..11] of String = (
    'Jahr 2419,'~,                                    // screen 1
    'UEE k'#123'mpft immer noch.'~,                        // screen 2
    'Nach 8 Jahren in der Armee hast du'~,            // screen 3
    'endlich deinen Vertrag beendet.'~,               // screen 3
    'Seit Langem hast du '#14'ber eigenes'~,              // screen 4
    'Unternehmen und '#14'ber die M'#15'glichkeit das'~,      // screen 4
    'zu tun was du willst, getr'#123'umt.'~,               // screen 4
    'F'#14'r den erhaltenen Scheck konntest du'~,         // screen 5
    'das billigste Schiff kaufen und das Geld'~,      // screen 5
    'blieb noch immer '#14'brig.'~,                       // screen 5
    'Es h'#123'ngt von dir ab, wohin du gehst...'~,        // screen 6
    ' Dr'#14'cke die Leertaste um fortzufahren '*~
);

  creditstxt: array [0..8] of TString = (
    'Programmierung'~,
    'MADRAFi'~,
    ''~,
    'Grafik'~,
    'Broniu KAZ'~,
    'MADRAFi'~,
    ''~,
    'Musik'~,
    'Caruso'~
    
);

