strings: array [0..11] of String = (
    'Jahr 2419,'~,                                      // screen 1
    'UEE k'#123'mpft immer noch.'~,          // screen 2
    'Nach 8 Jahren in der Armee hast du'~,             // screen 3
    'endlich deinen Vertrag beendet.'~,                // screen 3
    'Seit Langem hast du '#14'ber eigenes'~,          // screen 4
    'Unternehmen und '#14'ber die M'#15'glichkeit das'~,                // screen 4
    'zu tun was du willst, getr'#123'umt.'~,                              // screen 4
    'F'#14'r den Scheck, den du bekommen hast,'~,                         // screen 5
    'konntest du das billigste Schiff kaufen'~,              // screen 5
    'und immer noch etwas Ver'#123'nderung.'~,                // screen 5
    'Es h'#123'ngt von dir ab, wohin du gehst...'~,              // screen 6
    ' Dr'#14'cke die Leertaste um fortzufahren '*~
);

  creditstxt: array [0..9] of String = (
    'Programmierung'~,
    'MADRAFi'~,
    ''~,
    'Grafik'~,
    'Broniu KAZ'~,
    'MADRAFi'~,
    ''~,
    'Musik'~,
    'Caruso'~,
    ''~
    
);
