strings: array [0..11] of String = (
    'Das Jahr 2419,'~,                                    // screen 1
    'UEE kämpft immer noch.'~,                        // screen 2
    'Nach 8 Jahren in der Armee hast du'~,            // screen 3
    'endlich deinen Vertrag beendet.'~,               // screen 3
    'Seit Langem hast du von einem eigenen'~,         // screen 4
    'Unternehmen und von der Möglichkeit das'~,      // screen 4
    'zu tun was du willst, geträumt.'~,               // screen 4
    'Von dem erhaltenen Scheck konntest du'~,         // screen 5
    'das billigste Schiff kaufen und es blieb'~,      // screen 5
    'sogar noch etwas Geld übrig.'~,                  // screen 5
    'Es liegt nun an dir wohin du gehst...'~,        // screen 6
    ' Drücke die Leertaste um fortzufahren '*~
);

  creditstxt: array [0..9] of String = (
    'Programmierung'~,
    'MADRAFi'~,
    ''~,
    'Grafik'~,
    'Broniu KAZ'~,
    'MADRAFi'~,
    ''~,
    'Musik'~,
    'Caruso'~,
    ''~
    
);
