strings: array [0..11] of String = (
    'Jahr 2419,'~,                                      // screen 1
    'UEE kämpft immer noch.'~,          // screen 2
    'Nach 8 Jahren in der Armee hast du'~,             // screen 3
    'endlich deinen Vertrag beendet.'~,                // screen 3
    'Seit Langem hast du über eigenes'~,          // screen 4
    'Unternehmen und über die Möglichkeit das'~,                // screen 4
    'zu tun was du willst, geträumt.'~,                              // screen 4
    'Für den Scheck, den du bekommen hast,'~,                         // screen 5
    'konntest du das billigste Schiff kaufen'~,              // screen 5
    'und immer noch etwas Veränderung.'~,                // screen 5
    'Es hängt von dir ab, wohin du gehst...'~,              // screen 6
    ' Drücke die Leertaste um fortzufahren '*~
);

  creditstxt: array [0..9] of String = (
    'Programmierung'~,
    'MADRAFi'~,
    ''~,
    'Grafik'~,
    'Broniu KAZ'~,
    'MADRAFi'~,
    ''~,
    'Musik'~,
    'Caruso'~,
    ''~
    
);