
FREE_TOP = $4000;

DISPLAY_LIST_ADDRESS_TITLE = FREE_TOP;
//SCROLL_ADDRESS = DISPLAY_LIST_ADDRESS_TITLE + $100;
//STRINGS_ADDRESS = SCROLL_ADDRESS + $FA5;

//RMT_PLAYER_ADDRESS = $1000;
//RMT_MODULE_ADDRESS = $BF00;
//RMT_MODULE_ADDRESS = STRINGS_ADDRESS  + $500;
//RMT_PLAYER_ADDRESS = $AD00;
//RMT_MODULE_ADDRESS = RMT_PLAYER_ADDRESS + $800;
//RMT_PLAYER_ADDRESS = $BB00;


//CHARSET_ADDRESS = $D800;
GFX_ADDRESS = $5010;


// ***************************************************************************//


// ***************************************************************************//

//----------------------------------------------------------------------------//
