
FREE_TOP = $3000;

DISPLAY_LIST_ADDRESS_TITLE = FREE_TOP;
//SCROLL_ADDRESS = DISPLAY_LIST_ADDRESS_TITLE + $100;
//STRINGS_ADDRESS = SCROLL_ADDRESS + $100;
//RMT_PLAYER_ADDRESS = STRINGS_ADDRESS + $100;
//RMT_PLAYER_ADDRESS = DISPLAY_LIST_ADDRESS_TITLE + $100;
//RMT_MODULE_ADDRESS = RMT_PLAYER_ADDRESS + $800;

//CHARSET_ADDRESS = $D800;
GFX_ADDRESS = $9010;


// ***************************************************************************//


// ***************************************************************************//

//----------------------------------------------------------------------------//
