
FREE_TOP = $2000;

DISPLAY_LIST_ADDRESS_TITLE = FREE_TOP;
// CMC_PLAYER_ADDRESS = DISPLAY_LIST_ADDRESS_TITLE + $100;
// CMC_MODULE_ADDRESS = CMC_PLAYER_ADDRESS + $800;
PLAYER_ADDRESS = DISPLAY_LIST_ADDRESS_TITLE + $400;
MODULE_ADDRESS = PLAYER_ADDRESS + $800;

// PIC1_ADDRESS = CMC_MODULE_ADDRESS + $AAC;
PIC1_ADDRESS = MODULE_ADDRESS + $AAC;
PIC2_ADDRESS = PIC1_ADDRESS + 7684;
PIC3_ADDRESS = PIC2_ADDRESS + 7684;
// STRINGS_ADDRESS = PIC3_ADDRESS + 7684;


GFX_ADDRESS = $B010;
CHARSET_ADDRESS = $E400;

// ***************************************************************************//


// ***************************************************************************//

//----------------------------------------------------------------------------//
