strings: array [0..11] of String = (
    'Year 2419,'~,                                      // screen 1
    'United Earth Empire is still fighting.'~,          // screen 2
    'After 8 years in military, you have'~,             // screen 3
    'finally fulfilled your contract.'~,                // screen 3
    'For a long time you dreamed about your'~,          // screen 4
    'own ventures and to be able to do'~,                // screen 4
    'whatever you want.'~,                              // screen 4
    'With received pay check'~,                         // screen 5
    'you were able to buy cheapest ship'~,              // screen 5
    'and still have some change left.'~,                // screen 5
    'It is up to you, where to go now...'~,              // screen 6
    ' Press space bar to continue '*~
);

  creditstxt: array [0..9] of String = (
    'Programming'~,
    'MADRAFi'~,
    ''~,
    'Graphics'~,
    'Broniu'~,
    'Kaz'~,
    'MADRAFi'~,
    ''~,
    'Music'~,
    'Caruso'~
    
);