
locations: array [0..NUMBEROFLOCATIONS-1] of TString = (
'Port Alistair'~,
'Glum Hex'~,
'Gas Mine 158'~,
'Ambiguous Lab'~,
'Area 64'~,
'Kudrov Ore'~,
'Hydro Harvest'~,
'Hikers Research'~,
'Oasis Depot'~,
'Highdust'~,
'Yantar-4K2M'~,
'Tycho Station'~,
'Lourvil'~,
'LKRM-Westforge'~,
'LKRM-Sandy'~//,
// 'Cloud City'~,
// 'Mining Area 147'~,
// 'Cargo Depot'~,
// 'CyberTech'~,
// 'Fobos'~,
// 'Sakigake'~,
// 'Nozomi'~,
// 'Akatsuki'~,
// 'Novorossiysk'~,
// 'Rostov'~

);
