  creditstxt: array [0..9] of String = (
    'Programowanie'~,
    'MADRAFi'~,
    ''~,
    'Grafika'~,
    'Broniu Kaz'~,
    'MADRAFi'~,
    ''~,
    'Muzyka'~,
    'Caruso'~,
    ''~
    
);

  thankstxt: array [0..9] of String = (
    'Specjalne podziękowania:'~,
    ''~,
    'Bocianu za całe udzielone wsparcie'~,
    ''~,
    'XXL za pomoc z xBios'~,
    'Tebe za udzielone wsparcie z MAD-Pascalem'~,
    'Kaz za testowanie i doradzanie'~,
    'Dely za testy QA'~,
    ''~,
    ''~
);