  creditstxt: array [0..9] of String = (
    'Pomys'#12' i programowanie'~,
    'MADRAFi'~,
    ''~,
    'Grafika'~,
    'Broniu Kaz'~,
    'MADRAFi'~,
    ''~,
    'Muzyka'~,
    'Caruso'~,
    ''~
    
);

  thankstxt: array [0..9] of String = (
    'Specjalne podzi'#5'kowania:'~,
    ''~,
    'Bocianu za ca'#12'e udzielone wsparcie'~,
    ''~,
    'XXL za pomoc z xBios'~,
    'Tebe za udzielone wsparcie z MAD-Pascalem'~,
    'Kaz za testowanie i doradzanie'~,
    'Dely za testy QA'~,
    ''~,
    ''~
);
