  creditstxt: array [0..8] of TString = (
    'Programowanie'~,
    'MADRAFi'~,
    ''~,
    'Grafika'~,
    'Broniu Kaz'~,
    'MADRAFi'~,
    ''~,
    'Muzyka'~,
    'Caruso'~
    
);

  thankstxt: array [0..8] of String = (
    'Specjalne podzi'#5'kowania:'~,
    ''~,
    'Bocianu za ca'#12'e udzielone wsparcie'~,
    ''~,
    'XXL za pomoc z xBios'~,
    'Tebe za topowe wsparcie MAD-Pascala'~,
    'Kaz za testy i doradzanie'~,
    'Dely za testy QA'~,
    ''~
);
