strings: array [0..65] of String = (
    'v.0.38 (c) 2019 MADsoft'~, // 0
    'N'*'owa Gra'~,
    'W'*'yjście'~,
    '1'*' Nawigacja'~,
    '2'*' Konsola Handlu'~,
    '3'*' Napraw/Zatankuj'~, // 5
    '4'*' Baza Statków'~,
    'P'*'owrót'~,
    'Kup'~,
    'Sprz'~,
    '   Miejsce dostawy'~, // 10
    ' Przedmioty'~,
    'towar'~,
    ' cena'~,
    'Cały Ładunek'~,
    'Pusty Ładunek'~, // 15
    'A'*'nuluj'~,
    'O'*'K'~,
    '  za '~,
    '-Potwierdź'~,
    'Lok:'~, // 20
    'Naw:'~,
    'Odległość:'~,
    '-Nawigacja'~,
    'J'*'-Skok FTL'~,
    'Brak xBios, Brak Grafik'*~, // 25
    ' Wciśnij dowolny klawisz. '*~,
    ' Kupiłeś wybrany statek. '*~,
    ''~,
    'Zostałeś zaatakowany przez piratów.     Byłeś odważny i walczyłeś ile mogłeś.   Oszczędzili twoje życie w zamian za cały twój ładunek.'~,
    'Wystąpiła usterka systemu. Wybuch       uszkodził część twojego ładunku.'~, // 30
    'Zostałeś okradziony przez bandytów.     Straciłeś wszystkie swoje pieniądze.'~,
    'Zabrałeś ze sobą Pasażera. Zapłacił ci  za transport dodatkową gotówkę.'~,
    'Zobaczyłeś obywateli w pilnej potrzebie. Zdecydowałeś się im pomóc i rozdać część towarów.'~,
    'Zostałeć zobowiązany do użycia eskorty  wojskowej z powodu niedawnych działań   piratów. Zapłaciłeś standardową opłatę  serwisową.'~,
    'Wygląda na to, że Twój bilet na loterię wygrał. Nagroda została przesłana               na Twoje konto.'~, // 35
    ' Brak statków. '*~,
    'Nazw:'~,
    'Prod:'~,
    'Ładow:'~,
    'Cena :'~, // 40
    'Prędk:'~,
    'Długość:'~,
    'Masa:'~,
    '-Wybór'~,
    ' m/s'~, // 45
    ' metry'~,
    ' tony'~,
    ' Nie masz wystarczająco dużo'*~,
    ' Już posiadasz ten statek. '*~,
    '-Cały'~, // 50
    'K'*'ontynuacja'~,
    'Zapisz'~,
    'Wczytaj'~,
    'Slot '~,
    ' błąd'~, // 55
    ' udane'~,
    'Otwórz plik '~,
    'Autorzy'~,
    'QFuel:'~,
    ' Za mało paliwa kwantowego. '*~,  //60
    ' Twój statek nie wymaga tankowania. '*~,
    ' Twój statek został zatankowany. '*~,
    ' Za mało UEC do 100% tankowania. '*~,
    'Paliwo:'~,   
    'Łącznie:'~  //65

);