strings: array [0..65] of String = (
    'MADsoft'~, // 0
    'N'*'owa Gra'~,
    'W'*'yjście'~,
    '1'*' Nawigacja'~,
    '2'*' Konsola Handlu'~,
    '3'*' Napraw/Zatankuj'~, // 5
    '4'*' Baza Statków'~,
    'P'*'owrót'~,
    'Kupuj'~,
    'Sprzedaj'~,
    'Miejsce dostawy'~, // 10
    ' Przedmioty'~,
    'Towar'~,
    'Cena'~,
    'Ładowność'~,
    'Puste'~, // 15
    'A'*'nuluj'~,
    'O'*'K'~,
    '  za '~,
    '-Potwierdź'~,
    'Lok:'~, // 20
    'Naw:'~,
    'Odległość:'~,
    '-Nawigacja'~,
    #211'kok FTL'~,
    'Brak xBios, Brak Grafik'*~, // 25
    ' Naciśnij dowolny klawisz. '*~,
    ' Kupiłeś wybrany statek. '*~,
    ''~,
    'Zostałeś zaatakowany przez piratów.     Byłeś odważny i walczyłeś ile mogłeś.   Oszczędzili twoje życie w zamian za cały twój ładunek.'~,
    'Wystąpiła usterka systemu. Wybuch       uszkodził część twojego ładunku.'~, // 30
    'Zostałeś okradziony przez bandytów.     Straciłeś wszystkie swoje pieniądze.'~,
    'Zabrałeś ze sobą Pasażera. Zapłacił ci  za transport dodatkową gotówkę.'~,
    'Zobaczyłeś obywateli w pilnej potrzebie.Zdecydowałeś się im pomóc i oddając     część towarów.'~,
    'Zostałeć zobowiązany do użycia eskorty  wojskowej z powodu niedawnych działań   piratów. Zapłaciłeś standardową opłatę  serwisową.'~,
    'Wygląda na to, że Twój bilet na loterię wygrał. Nagroda została przesłana               na Twoje konto.'~, // 35
    ' Brak statków. '*~,
    'Nazwa:'~,
    'Prod:'~,
    'Ładowność:'~,
    'Cena:'~, // 40
    'Prędkość:'~,
    'Długość:'~,
    'Masa:'~,
    '-Wybór'~,
    ' m/s'~, // 45
    ' metry'~,
    ' tony'~,
    ' Nie masz wystarczająco dużo kredytów. '*~,
    ' Już posiadasz ten statek. '*~,
    '-Cały'~, // 50
    'K'*'ontynuacja'~,
    'Zapisanie'~,
    'Wczytanie'~,
    'Slot '~,
    ' błędne.'~, // 55
    ' udane.'~,
    'Otwórz plik '~,
    'A'#245'torzy'~,
    'QFuel:'~,
    ' Za mało paliwa kwantowego. '*~,  //60
    ' Twój statek nie wymaga tankowania. '*~,
    ' Twój statek został zatankowany. '*~,
    ' Za mało kredytów do 100% tankowania. '*~,
    'Paliwo:'~,   
    'Łącznie:'~  //65

);