strings: array [0..65] of String = (
    'MADsoft'~, // 0
    'N'*'owa Gra'~,
    'W'*'yj'#9'cie'~,
    '1'*' Nawigacja'~,
    '2'*' Konsola Handlu'~,
    '3'*' Napraw/Zatankuj'~, // 5
    '4'*' Baza Statk'#15'w'~,
    'P'*'owr'#15't'~,
    'Kupuj'~,
    'Sprzedaj'~,
    'Miejsce dostawy'~, // 10
    '    Przedmioty'~,
    'Towar'~,
    'Cena'~,
    ''#123'adowno'#9''#3''~,
    'Puste'~, // 15
    'A'*'nuluj'~,
    'O'*'K'~,
    ' za '~,
    '-Potwierd'#11''~,
    'Lok:'~, // 20
    'Cel:'~,
    'Odleg'#12'o'#9''#3':'~,
    '-Nawigacja'~,
    #211'kok FTL'~,
    'Brak xBios, Brak Grafik'*~, // 25
    ' Naci'#9'nij dowolny klawisz. '*~,
    ' Kupi'#12'e'#9' wybrany statek. '*~,
    ''~,
    'Zosta'#12'e'#9' zaatakowany przez pirat'#15'w.     By'#12'e'#9' odwa'#26'ny i walczy'#12'e'#9' ile mog'#12'e'#9'.   Oszcz'#5'dzili twoje '#26'ycie w zamian za ca'#12'y tw'#15'j '#12'adunek.'~,
    'Wyst'#2'pi'#12'a usterka systemu. Wybuch       uszkodzi'#12' cz'#5''#9''#3' twojego '#12'adunku.'~, // 30
    'Zosta'#12'e'#9' okradziony przez bandyt'#15'w.     Straci'#12'e'#9' wszystkie swoje pieni'#2'dze.'~,
    'Zabra'#12'e'#9' ze sob'#2' Pasa'#26'era. Zap'#12'aci'#12' ci  za transport dodatkow'#2' got'#15'wk'#5'.'~,
    'Zobaczy'#12'e'#9' obywateli w pilnej potrzebie.Zdecydowa'#12'e'#9' si'#5' im pom'#15'c i oddaj'#2'c     cz'#5''#9''#3' towar'#15'w.'~,
    'Zosta'#12'e'#3' zobowi'#2'zany do u'#26'ycia eskorty  wojskowej z powodu niedawnych dzia'#12'a'#14'   pirat'#15'w. Zap'#12'aci'#12'e'#9' standardow'#2' op'#12'at'#5'  serwisow'#2'.'~,
    'Wygl'#2'da na to, '#26'e Tw'#15'j bilet na loteri'#5' wygra'#12'. Nagroda zosta'#12'a przes'#12'ana               na Twoje konto.'~, // 35
    ' Brak statk'#15'w. '*~,
    'Nazwa:'~,
    'Prod:'~,
    ''#123'adowno'#9''#3':'~,
    'Cena:'~, // 40
    'Pr'#5'dko'#9''#3':'~,
    'D'#12'ugo'#9''#3':'~,
    'Masa:'~,
    '-Wyb'#15'r'~,
    ' m/s'~, // 45
    ' metry'~,
    ' tony'~,
    ' Nie masz wystarczaj'#2'co du'#26'o kredyt'#15'w. '*~,
    ' Ju'#26' posiadasz ten statek. '*~,
    '-Ca'#12'y'~, // 50
    'K'*'ontynuacja'~,
    'Zapisanie'~,
    'Wczytanie'~,
    'Slot '~,
    ' b'#12''#5'dne.'~, // 55
    ' udane.'~,
    'Otw'#15'rz plik '~,
    'A'#245'torzy'~,
    'QFuel:'~,
    ' Za ma'#12'o paliwa kwantowego. '*~,  //60
    ' Tw'#15'j statek nie wymaga tankowania. '*~,
    ' Tw'#15'j statek zosta'#12' zatankowany. '*~,
    ' Za ma'#12'o kredyt'#15'w do 100% tankowania. '*~,
    'Paliwo:'~,   
    ''#123''#2'cznie:'~  //65

);
