  creditstxt: array [0..8] of TString = (
    'Programming'~,
    'MADRAFi'~,
    ''~,
    'Graphics'~,
    'Broniu Kaz'~,
    'MADRAFi'~,
    ''~,
    'Music'~,
    'Caruso'~
    
);

  thankstxt: array [0..8] of String = (
    'Special thanks to:'~,
    ''~,
    'Bocianu for all the support'~,
    ''~,
    'XXL for xBios support'~,
    'Tebe for providing MAD-Pascal help'~,
    'Kaz for testing and advise'~,
    'Dely for QA testing'~,
    ''~
);