strings: array [0..66] of String = (
    'Congratulation!'~, // 0
    'N'*'ew Game'~,
    'Q'*'uit'~,
    '1'*' Navigation'~,
    '2'*' Trade Console'~,
    '3'*' Repair/Refuel Pad'~, // 5
    '4'*' Ship Depot'~,
    'B'*'ack'~,
    'Buy'~,
    'Sell'~,
    ' Delivery Location'~, // 10
    '  Available Items'~,
    'commodity'~,
    'price'~,
    'Total Cargo'~,
    'Empty Cargo'~, // 15
    'C'*'ancel'~,
    'O'*'K'~,
    ' for '~,
    '-Confirm'~,
    'Loc:'~, // 20
    'Nav:'~,
    'Distance:'~,
    '-Navigation'~,
    'J'*'-FTL Jump'~,
    'No xBios, No Pics'*~, // 25
    ' Press any key. '*~,
    'You`ve bought that ship.'*~,
    ''~,
    '  You have been boarded by pirates. You were brave and fought till you could.   They spared your life in exchange for   all of your cargo.'~,
    'There have been a system maltifunction. Explosion has damaged part of your      cargo.'~, // 30
    'You have been robed by some thugs.      You have lost all your money.'~,
    '   You have taken a Passenger with you. He payed you some extra cash for a ride.'~,
    'You saw some citizens in urgent need.   You decided to give away some goods.'~,
    'You were obligated to use military      escort due to recent pirate activities. You have paid standard service fee.'~,
    'It seems your lottery ticket won.       The prize has been transferred          to your account.'~, // 35
    ' No more ships. '*~,
    'Name:'~,
    'Prod:'~,
    'Cargo:'~,
    'Price:'~, // 40
    'Speed:'~,
    'Length:'~,
    'Mass:'~,
    '-Choose'~,
    ' m/s'~, // 45
    ' meters'~,
    ' tons'~,
    ' You do not have enough credits. '*~,
    ' You already own that ship. '*~,
    '-All'~, // 50
    'C'*'ontinue'~,
    'Save'~,
    'Load'~,
    'Slot '~,
    ' error'~, // 55
    ' successfull'~,
    'Open file '~,
    'C'#242'edits'~,
    'QFuel:'~,
    ' Not enough Quantum Fuel. '*~,  //60
    ' Your ship does not need refuel. '*~,
    ' Your ship has been refueled. '*~,
    ' Not enough credits to 100% refuel. '*~,
    'Refuel:'~,   
    'Total:'~,  //65
    'You have proven to be real king of the  commodity transportation. There were no  more challanges waiting for you, so you have retired.'~

);
