  creditstxt: array [0..8] of TString = (
    'Programmierung'~,
    'MADRAFi'~,
    ''~,
    'Grafik'~,
    'Broniu Kaz'~,
    'MADRAFi'~,
    ''~,
    'Musik'~,
    'Caruso'~
    
);

  thankstxt: array [0..8] of String = (
    'Besonderer dank:'~,
    ''~,
    'Bocianu for die ganze unterst'#14'tzung'~,
    ''~,
    'XXL f'#14'r xBios-Unterst'#14'tzung'~,
    'Tebe f'#14'r MAD-Pascal hilfe zu gaben'~,
    'Kaz f'#14'r Beratung'~,
    'Dely und CharlieChaplin f'#14'r QS-Tests'~,
    ''~
);