// keys

KEY_OPTION1 = 31;   //1
KEY_OPTION2 = 30;   //2
KEY_OPTION3 = 26;   //3
KEY_OPTION4 = 24;   //4
KEY_OPTION5 = 29;   //5
KEY_OPTION6 = 27;   //6

KEY_BACK = 23;      //z
KEY_QUIT = 16;      //v
KEY_NEW = 35;       //n
KEY_JUMP = 62;      //s
KEY_CREDITS = 11;   //u

KEY_BUYSELL = 33;   // space
KEY_SELECT = 12;    // return

KEY_UP = 14;
KEY_DOWN = 15;
KEY_LEFT = 6;
KEY_RIGHT = 7;
KEY_CTRLLEFT = 134;
KEY_CTRLRIGHT = 135;
KEY_SHIFTLEFT = 70;
KEY_SHIFTRIGHT = 71;


KEY_CANCEL = 63;  //a
KEY_CONT = 56;    //f

