strings: array [0..66] of String = (
    'Glückwunsch!'~, // 0
    'N'*'eues Spiel'~,
    'V'*'erlassen'~,
    '1'*' Navigation'~,
    '2'*' Handelskonsole'~,
    '3'*' Auftanken'~, // 5
    '4'*' Shiffsdepot'~,
    'Z'*'urück'~,
    'Kaufen'~,
    'Verkaufen'~,
    'Lieferort'~, // 10
    'Verfügbare Artikel'~,
    'Ware'~,
    'Preise'~,
    'Kapazität'~,
    'Leerer Raum'~, // 15
    'A'*'bbrechen'~,
    'O'*'K'~,
    ' für '~,
    '-Bestätigen'~,
    'Sta:'~, // 20
    'Nav:'~,
    'Entfernung:'~,
    '-Navigation'~,
    'S'*'-FTL Sprung'~,
    'Keine xBios, Kein Bilder'*~, // 25
    ' Drücke irgendeine Taste '*~,
    ' Du hast das Schiff gekauft. '*~,
    ''~,
    'Piraten haben dich attackiert. Du warst mutig und hast gekämpft bis zum Ende.   Sie haben dein Leben im Austausch für   deine Fracht verschont.'~,
    'Es hat einen Systemfehler gegeben. Die  Explosion hat einen Teil deiner Ladung  beschädigt.'~, // 30
    'Banditen haben dich bestohlen. Du hast  dein ganzes Geld verloren.'~,
    'Du hast einen Passagier mitgenommen.    Er hat dir zusätzliches Geld für ein    Transport gegeben.'~,
    'Du hast gesehen, das|s die Bürger         in Not sind. Du hast dich für schnelle  Hilfe entschieden und einen Teil deiner Waren verteilt.'~,
    'Wegen jüngster Aktivitäten der Piraten  wurdest du verpflichtet, eine           militärische Eskorte zu verwenden.      Du hast Standard-Gebühren dafür bezahlt.'~,
    'Es scheint, das|s dein Lottoschein        gewonnen hat. Der Gewinn wurde auf dein Konto überwiesen.'~, // 35
    ' Keine Schiffe mehr. '*~,
    'Name:'~,
    'Prod:'~,
    'Fracht:'~,
    'Preis:'~, // 40
    'Tempo:'~,
    'Länge:'~,
    'Masse:'~,
    '-Wählen'~,
    ' m/s'~, // 45
    ' meter'~,
    ' Tonnen'~,
    ' Du hast nicht genug Kredite '*~,
    ' Du besitzt dieses Schiff bereits. '*~,
    '-Alles'~, // 50
    'F'*'ortsetzen'~,
    'Speichern'~,
    'Laden'~,
    'Slot '~,
    ' fehler'~, // 55
    ' erfolgreich'~,
    'Datei öffnen '~,
    'A'#245'toren'~,
    'QFuel:'~,
    ' Nicht genug Quantentreibstoff. '*~,  //60
    ' Ihr Schiff mus|s nicht betankt werden. '*~,
    ' Ihr Schiff wurde betankt. '*~,
    ' Nicht genug UEC, um 100% zu tanken. '*~,
    'Tanken:'~,   
    'Gesamt:'~,  //65
    'Du bist ein wahrer Transportkönig. Das  hast du bewiesen. Auf dich warten keine neue Herausforderungen. Du gehst in den Ruhestand.'~

);
