strings: array [0..66] of String = (
    'Gl'#14'ckwunsch!'~, // 0
    'N'*'eues Spiel'~,
    'V'*'erla'#96'en'~,
    '1'*' Navigation'~,
    '2'*' Handel Konsole'~,
    '3'*' Auftanken Pad'~, // 5
    '4'*' Shiffsdepot'~,
    'Z'*'ur'#14'ck'~,
    'Kaufen'~,
    'Verkaufen'~,
    'Lieferort'~, // 10
    'Verf'#14'gbare Artikel'~,
    'Ware'~,
    'Preise'~,
    'Kapazit'#123't'~,
    'Leerer Raum'~, // 15
    'A'*'bbrechen'~,
    'O'*'K'~,
    ' f'#14'r '~,
    '-Best'#123'tigen'~,
    'Sta:'~, // 20
    'Nav:'~,
    'Abstand:'~,
    '-Navigation'~,
    'S'*'-FTL Springe'~,
    'Kein xBios, Kein Bilder'*~, // 25
    ' Dr'#14'cke irgendeine Taste '*~,
    ' Du hast das Schiff gekauft. '*~,
    ''~,
    'Piraten haben dich attackiert. Du warst mutig und hast gek'#123'mpft so lange es gingSie haben dein Leben im Austausch f'#14'r   deine Fracht geschont.'~,
    'Es hat einen Systemfehler gegeben. Die  Explosion hat einen Teil deiner Ladung  besch'#123'digt.'~, // 30
    'Banditen haben dich bestohlen. Du hast  dein ganzes Geld verloren.'~,
    'Du hast einen Pa'#96'agier mitgenommen.    Er hat dir zus'#123'tzliches Geld f'#14'r ein    Transport gegeben.'~,
    'Du hast gesehen, da'#96' die B'#14'rger        in Not sind. Du hast dich f'#14'r die Hilfe entschieden und hast einen Teil deiner  Waren verteilt.'~,
    'Wegen j'#14'ngster Aktivit'#123'ten der Piraten  wurdest du verpflichtet, eine           milit'#123'rische Eskorte zu verwenden.      Du hast Standard-Geb'#14'hren daf'#14'r bezahlt.'~,
    'Es scheint, da'#96' dein Lottoschein       gewonnen hat. Der Gewinn wurde auf dein Konto '#14'berwiesen.'~, // 35
    ' Keine Schiffe mehr. '*~,
    'Name:'~,
    'Prod:'~,
    'Kargo:'~,
    'Preis:'~, // 40
    'Speed:'~,
    'L'#123'nge:'~,
    'Masse:'~,
    '-W'#123'hlen'~,
    ' m/s'~, // 45
    ' meter'~,
    ' tonnen'~,
    ' Du hast nicht genug Kredite '*~,
    ' Du besitzt dieses Schiff bereits. '*~,
    '-Alles'~, // 50
    'F'*'ortsetzen'~,
    'Speichern'~,
    'Laden'~,
    'Slot '~,
    ' fehler'~, // 55
    ' erfolgreich'~,
    'Datei '#15'ffnen '~,
    'A'#245'toren'~,
    'QFuel:'~,
    ' Nicht genug Quantentreibstoff. '*~,  //60
    ' Ihr Schiff mu'#96' nicht betankt werden. '*~,
    ' Ihr Schiff wurde betankt. '*~,
    ' Nicht genug UEC, um 100% zu tanken. '*~,
    'Tanken:'~,   
    'Gesamt:'~,  //65
    'Du bist ein wahrer Transportk'#15'nig. Das  hast du bewiesen. Auf dich warten keine neue Herausforderungen. Du gehst in den Ruhestand.'~

);

