strings: array [0..65] of String = (
    'MADsoft'~, // 0
    'N'*'eues Spiel'~,
    'V'*'erlassen'~,
    '1'*' Navigation'~,
    '2'*' Handel Konsole'~,
    '3'*' Auftanken Pad'~, // 5
    '4'*' Shiffsdepot'~,
    'Z'*'urück'~,
    'Kaufen'~,
    'Verkaufen'~,
    'Lieferort'~, // 10
    'Verfügbare Artikel'~,
    'Ware'~,
    'Preise'~,
    'Kapazität'~,
    'Leerer Raum'~, // 15
    'A'*'bbrechen'~,
    'O'*'K'~,
    ' für '~,
    '-Bestätigen'~,
    'Sta:'~, // 20
    'Nav:'~,
    'Abstand:'~,
    '-Navigation'~,
    'S'*'-FTL Springe'~,
    'Kein xBios, Kein Bilder'*~, // 25
    ' Drücke irgendeine Taste. '*~,
    ' Du hast das Schiff gekauft. '*~,
    ''~,
    'Du wurdest von Piraten bestiegen.       Du warst mutig und hast gekämpft,       bis du konntest. Sie haben Ihr Leben    im Austausch für all Ihre Fracht        geschont.'~,
    'Es hat ein System Multifunction gegeben.Die Explosion hat einen Teil Ihrer      Ladung beschädigt.'~, // 30
    'Du wirst von einigen Schlägern          gekleidet. Sie haben Ihr ganzes Geld    verloren.'~,
    'Du hast einen Passagier mitgenommen.    Er hat dir extra Geld für eine Fahrt    bezahlt.'~,
    'Du hast einige dringend benötigte       Bürgergesehen. Du hast beschlossen,      einige Waren zu verschenken.'~,
    'Du wirst aufgrund der jüngsten          Piratenaktivitäten zur militärischen    Eskorte verpflichtet. Du hast           die Standard-Servicegebühr bezahlt.'~,
    'Es scheint, das Ihr Lottoschein         gewonnenhat. Der Preis wurde auf Ihr    Konto überwiesen.'~, // 35
    ' Keine Schiffe mehr. '*~,
    'Name:'~,
    'Prod:'~,
    'Kargo:'~,
    'Preis:'~, // 40
    'Speed:'~,
    'Länge:'~,
    'Mas|se:'~,
    '-Wählen'~,
    ' m/s'~, // 45
    ' meter'~,
    ' tonnen'~,
    ' Du hast nicht genug Kredite '*~,
    ' Du besitzt dieses Schiff bereits. '*~,
    '-Alles'~, // 50
    'F'*'ortsetzen'~,
    'Speichern'~,
    'Laden'~,
    'Slot '~,
    ' fehler'~, // 55
    ' erfolgreich'~,
    'Datei öffnen '~,
    'A'#245'toren'~,
    'QFuel:'~,
    ' Nicht genug Quantentreibstoff. '*~,  //60
    ' Ihr Schiff muss nicht betankt werden. '*~,
    ' Ihr Schiff wurde betankt. '*~,
    ' Nicht genug UEC, um 100% zu tanken. '*~,
    'Tanken:'~,   
    'Gesamt:'~  //65

);
