strings: array [0..65] of String = (
    'MADsoft'~, // 0
    'N'*'eues Spiel'~,
    'V'*'erla'#96'en'~,
    '1'*' Navigation'~,
    '2'*' Handel Konsole'~,
    '3'*' Auftanken Pad'~, // 5
    '4'*' Shiffsdepot'~,
    'Z'*'ur'#14'ck'~,
    'Kaufen'~,
    'Verkaufen'~,
    'Lieferort'~, // 10
    'Verf'#14'gbare Artikel'~,
    'Ware'~,
    'Preise'~,
    'Kapazit'#123't'~,
    'Leerer Raum'~, // 15
    'A'*'bbrechen'~,
    'O'*'K'~,
    ' f'#14'r '~,
    '-Best'#123'tigen'~,
    'Sta:'~, // 20
    'Nav:'~,
    'Abstand:'~,
    '-Navigation'~,
    'S'*'-FTL Springe'~,
    'Kein xBios, Kein Bilder'*~, // 25
    ' Dr'#14'cke irgendeine Taste. '*~,
    ' Du hast das Schiff gekauft. '*~,
    ''~,
    'Sie wurden von Piraten bestiegen. Du warst mutig und hast gek'#123'mpft, bis du konntest. Sie haben Ihr Leben im Austausch f'#14'r all Ihre Fracht geschont.'~,
    'Es hat ein System Multifunction gegeben. Die Explosion hat einen Teil Ihrer Ladung besch'#123'digt.'~, // 30
    'Sie wurden von einigen Schl'#123'gern gekleidet. Sie haben Ihr ganzes Geld verloren.'~,
    'Du hast einen Pa'#96'agier mitgenommen. Er hat dir extra Geld f'#14'r eine Fahrt bezahlt.'~,
    'Du hast einige dringend ben'#15'tigte       B'#14'rgergesehen. Sie haben beschlo'#96'en,   einige Waren zu verschenken.'~,
    'Du wirst aufgrund der j'#14'ngsten          Piratenaktivit'#123'ten zur milit'#123'rischen    Eskorte verpflichtet. Du hast           die Standard-Servicegeb'#14'hr bezahlt.'~,
    'Es scheint, das Ihr Lottoschein gewonnenhat. Der Preis wurde auf Ihr Konto      '#14'berwiesen.'~, // 35
    ' Keine Schiffe mehr. '*~,
    'Name:'~,
    'Prod:'~,
    'Kargo:'~,
    'Preis:'~, // 40
    'Speed:'~,
    'L'#123'nge:'~,
    'Masse:'~,
    '-W'#123'hlen'~,
    ' m/s'~, // 45
    ' meter'~,
    ' tonnen'~,
    ' Du hast nicht genug'*~,
    ' Du besitzt dieses Schiff bereits. '*~,
    '-Alles'~, // 50
    'F'*'ortsetzen'~,
    'Speichern'~,
    'Laden'~,
    'Slot '~,
    ' fehler'~, // 55
    ' erfolgreich'~,
    'Datei '#15'ffnen '~,
    'A'#245'toren'~,
    'QFuel:'~,
    ' Nicht genug Quantentreibstoff. '*~,  //60
    ' Ihr Schiff mu'#96' nicht betankt werden. '*~,
    ' Ihr Schiff wurde betankt. '*~,
    ' Nicht genug UEC, um 100% zu tanken. '*~,
    'Tanken:'~,   
    'Gesamt:'~  //65

);

