strings: array [0..66] of String = (
    'Glückwunsch!'~, // 0
    'N'*'eues Spiel'~,
    'V'*'erlassen'~,
    '1'*' Navigation'~,
    '2'*' Handel Konsole'~,
    '3'*' Auftanken Pad'~, // 5
    '4'*' Shiffsdepot'~,
    'Z'*'urück'~,
    'Kaufen'~,
    'Verkaufen'~,
    'Lieferort'~, // 10
    'Verfügbare Artikel'~,
    'Ware'~,
    'Preise'~,
    'Kapazität'~,
    'Leerer Raum'~, // 15
    'A'*'bbrechen'~,
    'O'*'K'~,
    ' für '~,
    '-Bestätigen'~,
    'Sta:'~, // 20
    'Nav:'~,
    'Abstand:'~,
    '-Navigation'~,
    'S'*'-FTL Springe'~,
    'Kein xBios, Kein Bilder'*~, // 25
    ' Drücke irgendeine Taste. '*~,
    ' Du hast das Schiff gekauft. '*~,
    ''~,
    'Piraten haben dich attackiert. Du warst mutig und hast gekämpft so lange es gingSie haben dein Leben im Austausch für   deine Fracht geschont.'~,
    'Es hat einen Systemfehler gegeben. Die  Explosion hat einen Teil deiner Ladung  beschädigt.'~, // 30
    'Banditen haben dich bestohlen. Du hast  dein ganzes Geld verloren.'~,
    'Du hast einen Passagier mitgenommen.    Er hat dir zusätzliches Geld für ein    Transport gegeben.'~,
    'Du hast gesehen, dass die Bürger        in Not sind. Du hast dich für die Hilfe entschieden und hast einen Teil deiner  Waren verteilt.'~,
    'Wegen jüngster Aktivitäten der Piraten  wurdest du verpflichtet, eine           militärische Eskorte zu verwenden.      Du hast Standard-Gebühren dafür bezahlt.'~,
    'Es scheint, dass dein Lottoschein       gewonnen hat. Der Gewinn wurde auf dein Konto überwiesen.'~, // 35
    ' Keine Schiffe mehr. '*~,
    'Name:'~,
    'Prod:'~,
    'Kargo:'~,
    'Preis:'~, // 40
    'Speed:'~,
    'Länge:'~,
    'Mas|se:'~,
    '-Wählen'~,
    ' m/s'~, // 45
    ' meter'~,
    ' tonnen'~,
    ' Du hast nicht genug Kredite '*~,
    ' Du besitzt dieses Schiff bereits. '*~,
    '-Alles'~, // 50
    'F'*'ortsetzen'~,
    'Speichern'~,
    'Laden'~,
    'Slot '~,
    ' fehler'~, // 55
    ' erfolgreich'~,
    'Datei öffnen '~,
    'A'#245'toren'~,
    'QFuel:'~,
    ' Nicht genug Quantentreibstoff. '*~,  //60
    ' Ihr Schiff muss nicht betankt werden. '*~,
    ' Ihr Schiff wurde betankt. '*~,
    ' Nicht genug UEC, um 100% zu tanken. '*~,
    'Tanken:'~,   
    'Gesamt:'~,  //65
    'Du bist König des Warentransports       erwiesen. Ohne Herausforderungen du hastin den Ruhestand getreten.'~

);
